import sqlite3, os
DB = os.path.join(os.path.dirname(__file__), 'iptv_billing', 'billing.db')
conn = sqlite3.connect(DB)
migrations = [
    """CREATE TABLE IF NOT EXISTS site_settings (
        key TEXT PRIMARY KEY, value TEXT NOT NULL, label TEXT,
        group_ TEXT DEFAULT 'general', type TEXT DEFAULT 'text',
        updated_at TEXT DEFAULT (datetime('now')))""",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('brand_name','IPTV Billing','Название сервиса','brand','text')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('trial_enabled','1','Пробный период','billing','bool')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('reg_enabled','1','Регистрация открыта','security','bool')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('cab_show_chat','1','Чат поддержки','cabinet','bool')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('cab_show_media','1','Раздел Медиа','cabinet','bool')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('min_topup','10','Мин. пополнение','billing','int')",
    "INSERT OR IGNORE INTO site_settings (key,value,label,group_,type) VALUES ('max_topup','50000','Макс. пополнение','billing','int')",
    """CREATE TABLE IF NOT EXISTS services (
        id INTEGER PRIMARY KEY, name TEXT NOT NULL, description TEXT,
        icon TEXT DEFAULT '📦', sort_order INTEGER DEFAULT 0,
        is_active INTEGER DEFAULT 1, created_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS packages (
        id INTEGER PRIMARY KEY,
        service_id INTEGER NOT NULL REFERENCES services(id),
        name TEXT NOT NULL, description TEXT,
        price_per_day REAL NOT NULL,
        connections INTEGER NOT NULL DEFAULT 1,
        is_active INTEGER DEFAULT 1, sort_order INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now')))""",
    "ALTER TABLE packages ADD COLUMN allow_extra_connections INTEGER DEFAULT 0",
    "ALTER TABLE packages ADD COLUMN extra_connection_price REAL DEFAULT 0.0",
    "ALTER TABLE packages ADD COLUMN max_extra_connections INTEGER DEFAULT 5",
    """CREATE TABLE IF NOT EXISTS user_packages (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        package_id INTEGER NOT NULL REFERENCES packages(id),
        extra_connections INTEGER NOT NULL DEFAULT 0,
        started_at TEXT DEFAULT (datetime('now')),
        active INTEGER DEFAULT 1, stopped_at TEXT)""",
    "ALTER TABLE user_packages ADD COLUMN extra_connections INTEGER NOT NULL DEFAULT 0",
    """CREATE TABLE IF NOT EXISTS charges (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        package_id INTEGER NOT NULL REFERENCES packages(id),
        amount REAL NOT NULL, charged_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS active_streams (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        stream_id TEXT NOT NULL,
        extra_connections INTEGER NOT NULL DEFAULT 1,
        started_at TEXT DEFAULT (datetime('now')),
        last_ping TEXT DEFAULT (datetime('now')),
        client_ip TEXT, UNIQUE(user_id, stream_id))""",
    """CREATE TABLE IF NOT EXISTS servers (
        id INTEGER PRIMARY KEY,
        package_id INTEGER NOT NULL REFERENCES packages(id),
        name TEXT NOT NULL, ip TEXT NOT NULL,
        proxy_port INTEGER NOT NULL DEFAULT 8080,
        api_port INTEGER NOT NULL DEFAULT 4444,
        comment TEXT, api_token TEXT DEFAULT '',
        is_active INTEGER DEFAULT 1, sort_order INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS user_server_prefs (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        package_id INTEGER NOT NULL REFERENCES packages(id),
        server_id INTEGER NOT NULL REFERENCES servers(id),
        updated_at TEXT DEFAULT (datetime('now')),
        UNIQUE(user_id, package_id))""",
    """CREATE TABLE IF NOT EXISTS chat_messages (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        from_admin INTEGER DEFAULT 0, body TEXT NOT NULL,
        is_read INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        action TEXT NOT NULL, details TEXT, ip TEXT,
        created_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS promocodes (
        id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL,
        type TEXT NOT NULL CHECK(type IN ('percent','fixed','days','trial')),
        value REAL NOT NULL, max_uses INTEGER DEFAULT 1, uses INTEGER DEFAULT 0,
        package_id INTEGER REFERENCES packages(id),
        valid_from TEXT, valid_until TEXT,
        is_active INTEGER DEFAULT 1, comment TEXT,
        created_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS promocode_uses (
        id INTEGER PRIMARY KEY,
        promocode_id INTEGER NOT NULL REFERENCES promocodes(id),
        user_id INTEGER NOT NULL REFERENCES users(id),
        discount_amount REAL DEFAULT 0,
        used_at TEXT DEFAULT (datetime('now')),
        UNIQUE(promocode_id, user_id))""",
    """CREATE TABLE IF NOT EXISTS notification_log (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        type TEXT NOT NULL, days_before INTEGER,
        sent_at TEXT DEFAULT (datetime('now')))""",
    """CREATE TABLE IF NOT EXISTS notify_settings (
        id INTEGER PRIMARY KEY DEFAULT 1,
        enabled INTEGER DEFAULT 1,
        days_before TEXT DEFAULT '7,3,1',
        trial_days INTEGER DEFAULT 3,
        trial_enabled INTEGER DEFAULT 1,
        updated_at TEXT DEFAULT (datetime('now')))""",
    "INSERT OR IGNORE INTO notify_settings (id) VALUES (1)",
    """CREATE TABLE IF NOT EXISTS smtp_settings (
        id INTEGER PRIMARY KEY DEFAULT 1,
        host TEXT DEFAULT 'smtp.yandex.ru', port INTEGER DEFAULT 465,
        user TEXT DEFAULT '', password TEXT DEFAULT '',
        from_name TEXT DEFAULT 'IPTV Billing',
        site_url TEXT DEFAULT 'http://localhost:5003',
        enabled INTEGER DEFAULT 1,
        updated_at TEXT DEFAULT (datetime('now')))""",
    "INSERT OR IGNORE INTO smtp_settings (id) VALUES (1)",
    """CREATE TABLE IF NOT EXISTS broadcasts (
        id INTEGER PRIMARY KEY, subject TEXT NOT NULL,
        body_html TEXT NOT NULL, filter_type TEXT DEFAULT 'all',
        filter_value TEXT, status TEXT DEFAULT 'draft',
        sent_count INTEGER DEFAULT 0,
        created_by INTEGER REFERENCES users(id),
        created_at TEXT DEFAULT (datetime('now')), sent_at TEXT)""",
    """CREATE TABLE IF NOT EXISTS referrals (
        id INTEGER PRIMARY KEY,
        referrer_id INTEGER NOT NULL REFERENCES users(id),
        referred_id INTEGER NOT NULL REFERENCES users(id),
        bonus_amount REAL DEFAULT 0.0, paid INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now')))""",
    "ALTER TABLE users ADD COLUMN phone TEXT",
    "ALTER TABLE users ADD COLUMN birthdate TEXT",
    "ALTER TABLE users ADD COLUMN avatar_url TEXT",
    "ALTER TABLE users ADD COLUMN timezone TEXT DEFAULT 'UTC'",
    "ALTER TABLE users ADD COLUMN language TEXT DEFAULT 'ru'",
    "ALTER TABLE users ADD COLUMN stream_format TEXT DEFAULT 'ts'",
    "ALTER TABLE users ADD COLUMN preferred_server TEXT",
    "ALTER TABLE users ADD COLUMN block_adult INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN auto_renew INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN email_news INTEGER DEFAULT 1",
    "ALTER TABLE users ADD COLUMN unsub_token TEXT",
    "ALTER TABLE users ADD COLUMN trial_used INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN comment TEXT",
    "ALTER TABLE users ADD COLUMN is_blocked INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN block_reason TEXT",
    "ALTER TABLE users ADD COLUMN last_login TEXT",
    "ALTER TABLE users ADD COLUMN last_ip TEXT",
    "ALTER TABLE users ADD COLUMN confirm_token TEXT",
    "ALTER TABLE users ADD COLUMN confirm_sent_at TEXT",
    "ALTER TABLE users ADD COLUMN reset_token TEXT",
    "ALTER TABLE users ADD COLUMN reset_token_exp TEXT",
    "ALTER TABLE users ADD COLUMN referral_code TEXT",
    "ALTER TABLE users ADD COLUMN referred_by INTEGER",
    "ALTER TABLE users ADD COLUMN updated_at TEXT DEFAULT (datetime('now'))",
    "CREATE INDEX IF NOT EXISTS idx_users_email  ON users(email)",
    "CREATE INDEX IF NOT EXISTS idx_users_login  ON users(login)",
    "CREATE INDEX IF NOT EXISTS idx_users_secret ON users(secret_token)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_up_active_unique ON user_packages(user_id, package_id) WHERE active=1",
    "CREATE INDEX IF NOT EXISTS idx_up_user      ON user_packages(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_up_active    ON user_packages(user_id, active)",
    "CREATE INDEX IF NOT EXISTS idx_charges_user ON charges(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_streams_user ON active_streams(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_chat_user    ON chat_messages(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_audit_user   ON audit_log(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_promo_code   ON promocodes(code)",
    "INSERT OR IGNORE INTO services (id,name,description,icon,sort_order) VALUES (1,'Телеканалы','Прямой эфир телевизионных каналов','📺',1)",
    "INSERT OR IGNORE INTO services (id,name,description,icon,sort_order) VALUES (2,'Медиатека','Фильмы, сериалы, передачи по запросу','🎬',2)",
    "INSERT OR IGNORE INTO services (id,name,description,icon,sort_order) VALUES (3,'Радио','Радиостанции онлайн','📻',3)",
    "INSERT OR IGNORE INTO services (id,name,description,icon,sort_order) VALUES (4,'Веб-камеры','Трансляции с веб-камер','📷',4)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (1,1,'Базовый','200+ каналов · SD',6.63,1,1)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (2,1,'Стандарт','400+ каналов · HD',11.63,2,2)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (3,1,'Премиум','600+ каналов · Full HD',19.97,4,3)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (4,1,'Ультра','800+ каналов · 4K + архив',33.30,6,4)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (5,2,'Медиатека','10 000+ фильмов и сериалов',9.97,2,1)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (6,3,'Радио','500+ радиостанций',3.30,1,1)",
    "INSERT OR IGNORE INTO packages (id,service_id,name,description,price_per_day,connections,sort_order) VALUES (7,4,'Камеры','1000+ веб-камер мира',3.30,1,1)",
]
ok = 0
skipped = 0
for sql in migrations:
    try:
        conn.execute(sql)
        print(f'OK:   {sql[:80]}')
        ok += 1
    except sqlite3.OperationalError as e:
        print(f'skip: {e}')
        skipped += 1
conn.commit()
conn.close()
print(f'\nMigration complete: {ok} applied, {skipped} skipped (already exist).')
